### ISSUE TITLE
Add Location to Users and Vendors

### ISSUE THREAD

**Issue by Angel591Diaz** [Gavalencia12/Mobile_Application#56]
# Add Location to Users and Vendors

## Issue Summary
Implement a feature to allow users and vendors to add and update their location information. This functionality will enable location-based features, such as finding nearby listings or targeting users based on location.

## Objectives
1. **Location Input for Users and Vendors**:
   - Enable users and vendors to add their location during registration or within their profile settings.
   - Allow users to update their location information as needed.

2. **Location-Based Features**:
   - Integrate location data to support future features like finding nearby listings or filtering search results based on proximity.

3. **Privacy and Security**:
   - Provide users and vendors with options to manage their location privacy.
   - Ensure location data is stored securely and used in compliance with privacy standards.

## Technical Details
- **Database**: Update user and vendor schemas to store location data (e.g., latitude, longitude, address).
- **Geolocation Integration**: Use geolocation services to allow users and vendors to set their location accurately.
- **Privacy Controls**: Implement options for users and vendors to choose whether their location is visible to others.

## Acceptance Criteria
- Users and vendors can add or update their location from their profiles.
- Location data is stored securely and is only accessible per user and vendor privacy preferences.
- Location-based features are functional and respect user privacy settings.

## Tasks
1. Update the database schema to include location fields for users and vendors.
2. Implement a geolocation input feature, allowing users and vendors to set or update their location.
3. Add privacy controls to manage the visibility of location information.
4. Test for usability, accuracy of location data, and compliance with privacy requirements.

## Notes
- Ensure compliance with location data handling and privacy best practices.
- Consider caching location data for efficiency if frequent updates are expected.

## Priority
Medium

**Comment by IsmaelMontiel710** [comment]
I don't understand the geolocation of the user, is it about their location? 

And does it have to be updated asynchronously in the buyer's or seller's profile?

**Comment by Angel591Diaz** [comment]
Actually, we had already discussed this in physical and came to the conclusion that it was just going to be a spinner with the locations which you already solved in your previous pr.
