### ISSUE TITLE
Add Search Engines to Key Sections

### ISSUE THREAD

**Issue by Angel591Diaz** [Gavalencia12/Mobile_Application#60]
# Add Search Engines to Key Sections

## Issue Summary
Implement search engines in key sections of the application to enhance usability and help users quickly locate relevant information. This feature will provide an efficient way to search through listings, user profiles, messages, and other critical sections.

## Objectives
1. **Section-Based Search**:
   - Add search functionality to key sections such as vehicle listings, user profiles, messages, and vendor catalogs.
   - Enable context-specific search fields that filter results based on each section’s content.

2. **Search Filtering and Sorting**:
   - Include basic filtering options in each section to refine search results (e.g., by relevance, date, location).
   - Provide sorting options to allow users to view results in their preferred order (e.g., newest first, highest rating).

3. **Real-Time Search Experience**:
   - Implement a real-time or predictive search experience where users see results as they type.
   - Ensure search performance remains optimal and responsive across all sections.

## Technical Details
- **Database Query Optimization**: Structure data and queries to support fast and accurate search results, including indexing frequently searched fields.
- **Search Algorithms**: Use appropriate search algorithms for each section to enhance result relevance and accuracy.
- **User Interface**: Design a search input with auto-suggestions or predictive text, as appropriate, to enhance usability.

## Acceptance Criteria
- Search functionality is implemented in key sections and returns relevant results based on user queries.
- Each section’s search engine includes filtering and sorting options for refining results.
- Real-time search provides fast and responsive feedback to users as they type.

## Tasks
1. Identify key sections requiring search functionality and define specific search parameters for each.
2. Optimize database queries and indexing for each section to support efficient search.
3. Implement real-time or predictive search functionality for improved user experience.
4. Design and implement a consistent search UI across all key sections.
5. Test search accuracy, performance, and usability across devices and sections.

## Notes
- Ensure search results align with user intent and maintain data privacy and security standards.
- Consider adding search history or recent searches for improved usability in future updates.

**Comment by IsmaelMontiel710** [comment]
Reconsider the issue there are sections that are not and will not be in the application

**Comment by Angel591Diaz** [comment]
Is not necessarily in all sections. This issue is for you to make the code of a search engine globally so that in the sections where it is necessary, call that search engine to avoid repeating code.
