### ISSUE TITLE
Vendor Qualification Interface

### ISSUE THREAD

**Issue by Angel591Diaz** [Gavalencia12/Mobile_Application#71]
## Issue Title
Vendor Qualification Interface

## Detailed Description
- **What is the issue?**  
  A Vendor Qualification Interface is needed to enable users to rate and review vendors based on their experience, as well as allow administrators to view and manage vendor ratings. This interface should help build trust in the platform and encourage high-quality service from vendors.

- **When does it occur?**  
  This feature is relevant whenever users complete transactions with vendors and wish to leave feedback, and whenever administrators need to oversee vendor ratings and reviews.

- **What part of the system does it affect?**  
  This affects the user and vendor profiles, the feedback system, and the administrative dashboard for review moderation.

- **Expected Behavior:**  
  Users should be able to rate vendors on a 5-star scale, leave written feedback, and view a vendor’s average rating on their profile. Administrators should be able to monitor, filter, and moderate these reviews.

- **Actual Behavior:**  
  Currently, there may be no structured interface for users to qualify vendors, limiting visibility into vendor quality and user trust-building.

## Steps to Reproduce
1. Complete a transaction with a vendor.
2. Attempt to leave a rating and review for the vendor.
3. Access the vendor profile to view aggregated ratings and reviews.
4. For administrators, attempt to access and moderate vendor reviews.

## Possible Solution
Develop a Vendor Qualification Interface where users can leave star ratings and written feedback for vendors, with these ratings visible on vendor profiles. Implement an admin view for monitoring and moderating reviews, with options to filter, hide, or respond to feedback if needed.

**Comment by Gavalencia12** [comment]
completed
